@startuml

participant Frontend
boundary BusController
control BusService
entity TabBus
control RabbitMQService
queue queue_keolis
control WebSocketServer
Frontend -> BusController: getBus()
BusController -> BusService: getBus()
BusService -> TabBus: getBus()
TabBus --> BusService: getBus()
BusService --> BusController: getBus()
BusController --> Frontend: getBus()
Frontend -> WebSocketServer: connect()
WebSocketServer --> Frontend: recupData()
BusService -> RabbitMQService: listenToRabbitMQ()
queue_keolis -> RabbitMQService: NewMessageOnListeningQueue
RabbitMQService -> WebSocketServer: send(msg: string)
WebSocketServer --> Frontend: recupData()
WebSocketServer --> BusService: stockData()


@enduml