@startuml SequenceCollector
participant Main
activate Main
create "Collector : Interface" as Col 
Main -> Col : Request(listUrl, time)
database "API Keolis" as API
activate Col
loop 
Main-> Col : GetRespond()
Col -> API : SendRequest()
API --> Col : HTTP
Col --> Main: JSON
Main-> Main: Sleep()
end

@enduml

@startuml SequenceLanchuer
participant Launcher
activate Launcher
create "CollectorStar : Collector" as Col
Launcher -> Col : createInstance()
activate Col
Col -> Col : Sub SequenceCollector

Launcher -> Launcher : wait()

@enduml
