@startuml ClassDiagramCollector

interface Collector {
    +getRespond() : dict
    -getRequest() : dict
}
class requestCollector{}

Collector <|-- requestCollector
Collector <|-- curlCollector
@enduml
