@startuml ComponentDiagram

component  "Star API Database" {
    portout HTTPRequestOut
}


component "Systeme"{
    portin HTTP_RequestIn
    Portout HTTP_PortOut
    database SQLite
    database Cache
    HTTP_RequestIn -> [collector]
    [collector] -> [RabbitMQ] :  send data to queue
    [RabbitMQ] -> [ProcessingAndStorageUnit] : send raw dada via queue

    [ProcessingAndStorageUnit] <-(0-> SQLite : store data and get data
    [ProcessingAndStorageUnit] <-0)- [IA_API]

    [RabbitMQ] --> [BackEnd] : send row data via queue
    [ProcessingAndStorageUnit] <-(0-> [BackEnd] : send parsed data
    [BackEnd] <-(0-> Cache : receive data
    [BackEnd] <-0)-> [FrontEnd] : echange data parsed
    
    [FrontEnd] ---> HTTP_PortOut
    

}

component "Web_page"{
    portin HTTP_PortIn
}

HTTPRequestOut --0)-> HTTP_RequestIn : send data
HTTP_PortOut ---> HTTP_PortIn : send web page to user

@enduml
