@startuml ComponentDiagram

component  "Star API Database" {
    portout HTTPRequestOut
}


component "Systeme"{
    portin HTTP_RequestIn
    Portout HTTP_PortOut
    database SQLite
    database Cache
    HTTP_RequestIn -> [collector]
    [collector] -> [RabbitMQ]
    [RabbitMQ] -> [ProcessingAndStorageUnit]

    [ProcessingAndStorageUnit] <-> SQLite

    [RabbitMQ] --> [BackEnd]
    [ProcessingAndStorageUnit] <--> [BackEnd]
    [BackEnd] <-> Cache
    [BackEnd] --> [FrontEnd]
    
    [FrontEnd] ---> HTTP_PortOut
    

}

component "Web_page"{
    portin HTTP_PortIn
}

HTTPRequestOut <--- HTTP_RequestIn
HTTP_PortOut <--- HTTP_PortIn

@enduml
