@startuml

left to right direction
actor "User" as user
rectangle System {
    usecase "Visualize Keolis network in realtime" as VisRT
    usecase "Visualize Keolis network at any time of the week" as VisSt
    usecase "Simulate the network by modifying parameters" as S
    usecase "Filter elements of network" as Filter
    usecase "Bus filling" as BF
}

user --> VisRT
VisRT --> Filter #line.dashed;
user --> VisSt
VisSt --> Filter #line.dashed;
user --> S

S --> BF #line.dashed;

@enduml
