@startuml sub sequence diagram for all buses position
autonumber
participant "Back-end" as BE
database    cache    as Ca
queue       "queue All buses Position Parse"  as QABPP
participant "Processing and storage unit" as UTS
queue       "queue All buses Position Raw" as QABPR
participant Collector as Co
database    "Star database API"    as DBStar

loop every 30 seconds
    Co -> DBStar : send request to get all buses position
    DBStar --> Co : return all buses position raw
    Co -> QABPR : buses Positions raw
    QABPR -> UTS : buses Positions raw
    UTS -> QABPP : buses Positions parse
    QABPP -> BE : buses Positions parse
    BE -> Ca : buses Positions parse
end
@enduml



@startuml sub sequence diagram for buses schedules
autonumber
database    database    as DB
participant "Processing and storage unit" as UTS
queue       "queue All buses schedule" as QABS
participant Collector as Co
database    databaseStar    as DBStar

loop every days
    Co -> DBStar : send request to get all buses schedules
    DBStar --> Co : return all buses schedules Raw
    Co -> QABS : buses schedules Raw
    QABS -> UTS : buses schedules Raw
    UTS -> DB : buses schedules Parse
end
@enduml





@startuml sub  diagram for Maximum attendance level
autonumber
database    database    as DB
participant "Processing and storage unit" as UTS
queue       "queue Maximum attendance level" as QMAL
participant Collector as Co
database    databaseStar    as DBStar

loop every days
    Co -> DBStar : send request to get all Maximum attendance level
    DBStar --> Co : return all Maximum attendance level Raw
    Co -> QMAL : Maximum attendance level Raw
    QMAL -> UTS : Maximum attendance level Raw
    UTS -> DB : Maximum attendance level Parse
end

@enduml



@startuml sub sequence diagram visualization of all buses 
autonumber
actor       User       as U
participant "Front-end" as FE
participant "Back-end" as BE
database    cache    as Ca

U -> FE : request all buses position
FE -> BE : request all buses position
BE -> Ca : request all buses position
Ca --> BE : return all buses position
BE --> FE : return all buses position
FE --> U : display all buses position

@enduml


@startuml sub sequence diagram simulation
autonumber
actor       User       as U
participant "Front-end" as FE
participant "Back-end" as BE
database    cache    as Ca
participant "Processing and storage unit" as UTS

U -> FE : request simulation
FE -> BE : request simulation
BE -> Ca : request data for simulation
Ca --> BE : return data for simulation
BE -> UTS : create a simulation
UTS --> BE : return simulation
BE --> FE : return simulation
FE --> U : display simulation
@enduml



@startuml sub sequence diagram collector fail
autonumber
participant "Processing and storage unit" as UTS
queue       "queue All buses Position Raw" as QABPR
participant Collector as Co
database    "Star database API"    as DBStar

loop every 30 seconds
    Co -> DBStar : send request
    DBStar --> Co : return fail
    Co -> QABPR : error message
    QABPR -> UTS : error message
    UTS -> UTS : log error message
end
@enduml


@startuml sub sequence diagram get cache fail
autonumber
actor       User       as U
participant "Front-end" as FE
participant "Back-end" as BE
database    cache    as Ca

U -> FE : request something
FE -> BE : request something
BE -> Ca : request something
Ca --> BE : return error message fail to conect to cache
BE --> FE : return error message
FE --> U : display error message
@enduml


@startuml sub sequence diagram Backend fail
autonumber
actor       User       as U
participant "Front-end" as FE
participant "Back-end" as BE

U -> FE : request something
FE -> BE : request something
BE --> FE : return error message
FE --> U : display error message
@enduml


@startuml sub sequence diagram simulation fail
autonumber
actor       User       as U
participant "Front-end" as FE
participant "Back-end" as BE
database    cache    as Ca
participant "Processing and storage unit" as UTS

U -> FE : request simulation
FE -> BE : request simulation
BE -> Ca : request data for simulation
Ca --> BE : return data for simulation
BE -> UTS : create a simulation
UTS --> BE : return error message
BE --> FE : return error message
FE --> U : display error message
@enduml