@startuml sub sequence diagram simulation
autonumber
actor       User       as U
participant "Front-end" as FE
participant "Back-end" as BE
participant "Processing and storage unit" as UTS

U -> FE : request simulation
FE -> BE : request simulation

BE -> UTS : create a simulation
UTS --> BE : return simulation
BE --> FE : return simulation
FE --> U : display simulation
@enduml